[package]
name = "pixelflut-filler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
structopt = "0.3.22"
gif = "0.11.3"
flate2 = "1.0.23"